/* Generated by Frama-C */
#include "pthread.h"
#include "sched.h"
#include "signal.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "stdlib.h"
#include "time.h"
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

/*@ requires valid_nptr: valid_read_string(nptr);
    assigns \result;
    assigns \result
      \from (indirect: nptr), (indirect: *(nptr + (0 .. strlen{Old}(nptr))));
 */
int __gen_e_acsl_atoi(char const *nptr);

int a;
char *n = (char *)"134";
int main(int argc, char **argv)
{
  int __retres;
  __e_acsl_memory_init(& argc,& argv,8UL);
  argc = __gen_e_acsl_atoi((char const *)n);
  a = argc;
  __retres = 0;
  __e_acsl_memory_clean();
  return __retres;
}

/*@ requires valid_nptr: valid_read_string(nptr);
    assigns \result;
    assigns \result
      \from (indirect: nptr), (indirect: *(nptr + (0 .. strlen{Old}(nptr))));
 */
int __gen_e_acsl_atoi(char const *nptr)
{
  int __retres;
  __retres = atoi(nptr);
  return __retres;
}


