  $ frama-c -no-autoload-plugins -check custom_machdep.c -machdep custom_machdep.yaml -print
  [kernel] Parsing custom_machdep.c (with preprocessing)
  /* Generated by Frama-C */
  #include "ctype.h"
  #include "errno.h"
  #include "inttypes.h"
  #include "locale.h"
  #include "math.h"
  #include "signal.h"
  #include "stdarg.h"
  #include "stddef.h"
  #include "stdint.h"
  #include "stdio.h"
  #include "stdlib.h"
  #include "string.h"
  #include "strings.h"
  #include "time.h"
  #include "wchar.h"
  int main(void)
  {
    int __retres;
    __retres = 8388607 - 1;
    return __retres;
  }
  
  




Note: we can't use only -D below, as the __fc_machdep.h define takes precedence. With -U, our cmdline definition is used in the code
  $ frama-c -no-autoload-plugins -check custom_machdep.c -cpp-extra-args="-UCUSTOM_MACHDEP -DCUSTOM_MACHDEP=42" -machdep custom_machdep.yaml -print
  [kernel] Parsing custom_machdep.c (with preprocessing)
  /* Generated by Frama-C */
  #include "ctype.h"
  #include "errno.h"
  #include "inttypes.h"
  #include "locale.h"
  #include "math.h"
  #include "signal.h"
  #include "stdarg.h"
  #include "stddef.h"
  #include "stdint.h"
  #include "stdio.h"
  #include "stdlib.h"
  #include "string.h"
  #include "strings.h"
  #include "time.h"
  #include "wchar.h"
  int main(void)
  {
    int __retres;
    __retres = 8388607 - 42;
    return __retres;
  }
  
  




We want to ensure that `-load` works independently of in which directory the
corresponding `-save` was performed
  $ frama-c -no-autoload-plugins -check -machdep custom_machdep.yaml custom_machdep.c -save custom_machdep.sav -print
  [kernel] Parsing custom_machdep.c (with preprocessing)
  /* Generated by Frama-C */
  #include "ctype.h"
  #include "errno.h"
  #include "inttypes.h"
  #include "locale.h"
  #include "math.h"
  #include "signal.h"
  #include "stdarg.h"
  #include "stddef.h"
  #include "stdint.h"
  #include "stdio.h"
  #include "stdlib.h"
  #include "string.h"
  #include "strings.h"
  #include "time.h"
  #include "wchar.h"
  int main(void)
  {
    int __retres;
    __retres = 8388607 - 1;
    return __retres;
  }
  
  



  $ mkdir -p subdir && (cd subdir && frama-c -no-autoload-plugins -load ../custom_machdep.sav -print)
  /* Generated by Frama-C */
  #include "ctype.h"
  #include "errno.h"
  #include "inttypes.h"
  #include "locale.h"
  #include "math.h"
  #include "signal.h"
  #include "stdarg.h"
  #include "stddef.h"
  #include "stdint.h"
  #include "stdio.h"
  #include "stdlib.h"
  #include "string.h"
  #include "strings.h"
  #include "time.h"
  #include "wchar.h"
  int main(void)
  {
    int __retres;
    __retres = 8388607 - 1;
    return __retres;
  }
  
  
