/* Generated by Frama-C */
typedef unsigned char uint8;
typedef unsigned short uint16;
typedef unsigned long uint32;
extern uint32 const t[2];

uint32 s[2];
/*@
predicate equal_t_s{L}(ℤ i) =
  \at(t[i] ≡
      (unsigned long)((uint16)(*((uint8 *)((uint32 *)s) + i) ≡
                               *(((uint8 *)((uint32 *)s) + i) + 1))),
      L);
 */
uint8 Array[10];
/*@ ghost uint32 FCG_Number; */
/*@ ghost uint32 FCG_Var1[1000]; */
/*@ ghost uint32 FCG_Var2[1000]; */
/*@
predicate mypredl{L}=
  ∀ ℤ MyNum;
    0 ≤ MyNum < FCG_Number ⇒
    FCG_Var2[MyNum] ≡
    (unsigned long)((uint16)(*((uint8 *)(&Array[FCG_Var1[MyNum]] + 1)) * 256
                             +
                             *((uint8 *)((&Array[FCG_Var1[MyNum]] + (1 + 2))
                                         + 1))));
 */

