/* Generated by Frama-C */
#include "pthread.h"
#include "sched.h"
#include "signal.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "time.h"
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

/*@ axiomatic p {
      predicate p(integer s) ;
      
      }

*/
/*@ ensures p(\old(s)); */
void __gen_e_acsl_f(int s);

void f(int s)
{
  return;
}

int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __gen_e_acsl_f(2);
  __retres = 0;
  __e_acsl_memory_clean();
  return __retres;
}

/*@ axiomatic g {
      logic integer g(int c) 
        reads c;
      
      }

*/
/*@ ensures g(\old(t)) == 0; */
int __gen_e_acsl_h(int const t);

int h(int const t)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int i(void)
{
  int __retres;
  __gen_e_acsl_h(1);
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Assertion";
    __gen_e_acsl_assert_data.pred_txt = "\\false";
    __gen_e_acsl_assert_data.file = "axiomatic.c";
    __gen_e_acsl_assert_data.fct = "i";
    __gen_e_acsl_assert_data.line = 36;
    __gen_e_acsl_assert_data.name = "missing_return";
    __e_acsl_assert(0,& __gen_e_acsl_assert_data);
  }
  /*@ assert missing_return: \false; */ ;
  __retres = 0;
  return __retres;
}

/*@ ensures g(\old(t)) == 0; */
int __gen_e_acsl_h(int const t)
{
  int __gen_e_acsl_at;
  int __retres;
  __gen_e_acsl_at = t;
  __retres = h(t);
  return __retres;
}

/*@ ensures p(\old(s)); */
void __gen_e_acsl_f(int s)
{
  int __gen_e_acsl_at;
  __gen_e_acsl_at = s;
  f(s);
  return;
}


