  $ frama-c-script make-machdep --compiler clang --cpp-arch-flags='--target=x86_64' | yq -Y 'del(.version)|del(.custom_defs)'
  alignof_aligned: 16
  alignof_double: 8
  alignof_float: 4
  alignof_fun: 4
  alignof_int: 4
  alignof_long: 8
  alignof_longdouble: 16
  alignof_longlong: 8
  alignof_ptr: 8
  alignof_short: 2
  alignof_str: 1
  max_align_t: long double
  bufsiz: '8192'
  char_is_unsigned: false
  compiler: clang
  cpp_arch_flags:
    - --target=x86_64
  eof: (-1)
  errno:
    edom: '33'
    eilseq: '84'
    erange: '34'
    e2big: '7'
    eacces: '13'
    eaddrinuse: '98'
    eaddrnotavail: '99'
    eafnosupport: '97'
    eagain: '11'
    ealready: '114'
    ebade: '52'
    ebadf: '9'
    ebadfd: '77'
    ebadmsg: '74'
    ebadr: '53'
    ebadrqc: '56'
    ebadslt: '57'
    ebusy: '16'
    ecanceled: '125'
    echild: '10'
    echrng: '44'
    ecomm: '70'
    econnaborted: '103'
    econnrefused: '111'
    econnreset: '104'
    edeadlk: '35'
    edeadlock: '35'
    edestaddrreq: '89'
    edquot: '122'
    eexist: '17'
    efault: '14'
    efbig: '27'
    ehostdown: '112'
    ehostunreach: '113'
    eidrm: '43'
    einprogress: '115'
    eintr: '4'
    einval: '22'
    eio: '5'
    eisconn: '106'
    eisdir: '21'
    eisnam: '120'
    ekeyexpired: '127'
    ekeyrejected: '129'
    ekeyrevoked: '128'
    el2hlt: '51'
    el2nsync: '45'
    el3hlt: '46'
    el3rst: '47'
    elibacc: '79'
    elibbad: '80'
    elibmax: '82'
    elibscn: '81'
    elibexec: '83'
    eloop: '40'
    emediumtype: '124'
    emfile: '24'
    emlink: '31'
    emsgsize: '90'
    emultihop: '72'
    enametoolong: '36'
    enetdown: '100'
    enetreset: '102'
    enetunreach: '101'
    enfile: '23'
    enobufs: '105'
    enodata: '61'
    enodev: '19'
    enoent: '2'
    enoexec: '8'
    enokey: '126'
    enolck: '37'
    enolink: '67'
    enomedium: '123'
    enomem: '12'
    enomsg: '42'
    enonet: '64'
    enopkg: '65'
    enoprotoopt: '92'
    enospc: '28'
    enosr: '63'
    enostr: '60'
    enosys: '38'
    enotblk: '15'
    enotconn: '107'
    enotdir: '20'
    enotempty: '39'
    enotrecoverable: '131'
    enotsock: '88'
    enotsup: '95'
    enotty: '25'
    enotuniq: '76'
    enxio: '6'
    eopnotsupp: '95'
    eoverflow: '75'
    eownerdead: '130'
    eperm: '1'
    epfnosupport: '96'
    epipe: '32'
    eproto: '71'
    eprotonosupport: '93'
    eprototype: '91'
    eremchg: '78'
    eremote: '66'
    eremoteio: '121'
    erestart: '85'
    erofs: '30'
    eshutdown: '108'
    espipe: '29'
    esocktnosupport: '94'
    esrch: '3'
    estale: '116'
    estrpipe: '86'
    etime: '62'
    etimedout: '110'
    etxtbsy: '26'
    euclean: '117'
    eunatch: '49'
    eusers: '87'
    ewouldblock: '11'
    exdev: '18'
    exfull: '54'
  filename_max: '4096'
  fopen_max: '16'
  has__builtin_va_list: true
  host_name_max: '64'
  int_fast8_t: signed char
  int_fast16_t: long
  int_fast32_t: long
  int_fast64_t: long
  intptr_t: long
  l_tmpnam: '20'
  little_endian: true
  machdep_name: anonymous_machdep
  mb_cur_max: ((size_t)16)
  nsig: (64 + 1)
  path_max: '4096'
  posix_version: 200809L
  ptrdiff_t: long
  rand_max: '2147483647'
  sig_atomic_t: int
  size_t: unsigned long
  sizeof_double: 8
  sizeof_float: 4
  sizeof_fun: 1
  sizeof_int: 4
  sizeof_long: 8
  sizeof_longdouble: 16
  sizeof_longlong: 8
  sizeof_ptr: 8
  sizeof_short: 2
  sizeof_void: 1
  ssize_t: long
  time_t: long
  tmp_max: '238328'
  tty_name_max: '32'
  uint_fast8_t: unsigned char
  uint_fast16_t: unsigned long
  uint_fast32_t: unsigned long
  uint_fast64_t: unsigned long
  uintptr_t: unsigned long
  wchar_t: int
  weof: (0xffffffffu)
  wint_t: int
  wordsize: '64'
