/* Generated by Frama-C */
#include "pthread.h"
#include "sched.h"
#include "signal.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "time.h"
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

int __gen_e_acsl_empty_block_here(void *s);

int __gen_e_acsl_valid_or_empty_here(void *s, unsigned long n);

int __gen_e_acsl_valid_read_or_empty_here(void *s, unsigned long n);

/*@ requires valid_dest: valid_or_empty(dest, n);
    requires valid_src: valid_read_or_empty(src, n);
    requires
      separation:
        \separated((char *)dest + (0 .. n - 1), (char *)src + (0 .. n - 1));
    ensures
      copied_contents:
        memcmp{Post, Pre}((char *)\old(dest), (char *)\old(src), \old(n)) ==
        0;
    ensures result_ptr: \result == \old(dest);
    assigns *((char *)dest + (0 .. n - 1)), \result;
    assigns *((char *)dest + (0 .. n - 1))
      \from *((char *)src + (0 .. n - 1));
    assigns \result \from dest;
 */
void *__gen_e_acsl_memcpy(void * restrict dest, void const * restrict src,
                          size_t n);

/*@ requires valid_s: valid_or_empty(s, n);
    ensures acsl_c_equiv: memset((char *)\old(s), \old(c), \old(n)) == \true;
    ensures result_ptr: \result == \old(s);
    assigns *((char *)s + (0 .. n - 1)), \result;
    assigns *((char *)s + (0 .. n - 1)) \from c;
    assigns \result \from s;
 */
void *__gen_e_acsl_memset(void *s, int c, size_t n);

int main(void)
{
  int __retres;
  int *src[2];
  int *dest[2];
  int *tmp_1;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __e_acsl_store_block((void *)(& tmp_1),8UL);
  __e_acsl_store_block((void *)(dest),16UL);
  __e_acsl_store_block((void *)(src),16UL);
  int a = 111;
  __e_acsl_store_block((void *)(& a),4UL);
  __e_acsl_full_init((void *)(& a));
  int b = 222;
  __e_acsl_store_block((void *)(& b),4UL);
  __e_acsl_full_init((void *)(& b));
  int size = (int)(sizeof(int *) * (unsigned long)2);
  __e_acsl_initialize((void *)(src),sizeof(int *));
  __e_acsl_temporal_store_nblock((void *)(src),(void *)(& a));
  src[0] = & a;
  __e_acsl_initialize((void *)(& src[1]),sizeof(int *));
  __e_acsl_temporal_store_nblock((void *)(& src[1]),(void *)(& b));
  src[1] = & b;
  __e_acsl_initialize((void *)(dest),sizeof(int *));
  __e_acsl_temporal_store_nblock((void *)(dest),(void *)0);
  dest[0] = (int *)0;
  __e_acsl_initialize((void *)(& dest[1]),sizeof(int *));
  __e_acsl_temporal_store_nblock((void *)(& dest[1]),(void *)0);
  dest[1] = (int *)0;
  {
    int __gen_e_acsl_initialized;
    int __gen_e_acsl_and;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __gen_e_acsl_initialized = __e_acsl_initialized((void *)(src),
                                                    sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data,"(int **)src",
                                 (void *)(src));
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,
                                 "\\initialized((int **)src)",0,
                                 __gen_e_acsl_initialized);
    if (__gen_e_acsl_initialized) {
      int __gen_e_acsl_valid;
      __gen_e_acsl_valid = __e_acsl_valid((void *)src[0],sizeof(int),
                                          (void *)src[0],(void *)(src));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data,"src[0]",
                                   (void *)src[0]);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,
                                   "\\valid(src[0])",0,__gen_e_acsl_valid);
      __gen_e_acsl_and = __gen_e_acsl_valid;
    }
    else __gen_e_acsl_and = 0;
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Assertion";
    __gen_e_acsl_assert_data.pred_txt = "\\valid(src[0])";
    __gen_e_acsl_assert_data.file = "t_memcpy.c";
    __gen_e_acsl_assert_data.fct = "main";
    __gen_e_acsl_assert_data.line = 20;
    __e_acsl_assert(__gen_e_acsl_and,& __gen_e_acsl_assert_data);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data);
  }
  /*@ assert \valid(src[0]); */ ;
  {
    int __gen_e_acsl_initialized_2;
    int __gen_e_acsl_and_2;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_2 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_2 = __e_acsl_initialized((void *)(& src[1]),
                                                      sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_2,"&src[1]",
                                 (void *)(& src[1]));
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_2,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_2,
                                 "\\initialized(&src[1])",0,
                                 __gen_e_acsl_initialized_2);
    if (__gen_e_acsl_initialized_2) {
      int __gen_e_acsl_valid_2;
      __gen_e_acsl_valid_2 = __e_acsl_valid((void *)src[1],sizeof(int),
                                            (void *)src[1],
                                            (void *)(& src[1]));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_2,"src[1]",
                                   (void *)src[1]);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_2,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_2,
                                   "\\valid(src[1])",0,__gen_e_acsl_valid_2);
      __gen_e_acsl_and_2 = __gen_e_acsl_valid_2;
    }
    else __gen_e_acsl_and_2 = 0;
    __gen_e_acsl_assert_data_2.blocking = 1;
    __gen_e_acsl_assert_data_2.kind = "Assertion";
    __gen_e_acsl_assert_data_2.pred_txt = "\\valid(src[1])";
    __gen_e_acsl_assert_data_2.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_2.fct = "main";
    __gen_e_acsl_assert_data_2.line = 21;
    __e_acsl_assert(__gen_e_acsl_and_2,& __gen_e_acsl_assert_data_2);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_2);
  }
  /*@ assert \valid(src[1]); */ ;
  __e_acsl_temporal_reset_parameters();
  __e_acsl_temporal_reset_return();
  __e_acsl_temporal_save_nblock_parameter((void *)(& dest),0U);
  __e_acsl_temporal_save_nblock_parameter((void *)(& src),1U);
  __gen_e_acsl_memcpy((void *)(& dest),(void const *)(& src),(size_t)size);
  {
    int __gen_e_acsl_initialized_3;
    int __gen_e_acsl_and_3;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_3 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_3 = __e_acsl_initialized((void *)(dest),
                                                      sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_3,"(int **)dest",
                                 (void *)(dest));
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_3,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_3,
                                 "\\initialized((int **)dest)",0,
                                 __gen_e_acsl_initialized_3);
    if (__gen_e_acsl_initialized_3) {
      int __gen_e_acsl_valid_3;
      __gen_e_acsl_valid_3 = __e_acsl_valid((void *)dest[0],sizeof(int),
                                            (void *)dest[0],(void *)(dest));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_3,"dest[0]",
                                   (void *)dest[0]);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_3,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_3,
                                   "\\valid(dest[0])",0,__gen_e_acsl_valid_3);
      __gen_e_acsl_and_3 = __gen_e_acsl_valid_3;
    }
    else __gen_e_acsl_and_3 = 0;
    __gen_e_acsl_assert_data_3.blocking = 1;
    __gen_e_acsl_assert_data_3.kind = "Assertion";
    __gen_e_acsl_assert_data_3.pred_txt = "\\valid(dest[0])";
    __gen_e_acsl_assert_data_3.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_3.fct = "main";
    __gen_e_acsl_assert_data_3.line = 25;
    __e_acsl_assert(__gen_e_acsl_and_3,& __gen_e_acsl_assert_data_3);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_3);
  }
  /*@ assert \valid(dest[0]); */ ;
  {
    int __gen_e_acsl_initialized_4;
    int __gen_e_acsl_and_4;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_4 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_4 = __e_acsl_initialized((void *)(& dest[1]),
                                                      sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_4,"&dest[1]",
                                 (void *)(& dest[1]));
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,
                                 "\\initialized(&dest[1])",0,
                                 __gen_e_acsl_initialized_4);
    if (__gen_e_acsl_initialized_4) {
      int __gen_e_acsl_valid_4;
      __gen_e_acsl_valid_4 = __e_acsl_valid((void *)dest[1],sizeof(int),
                                            (void *)dest[1],
                                            (void *)(& dest[1]));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_4,"dest[1]",
                                   (void *)dest[1]);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,
                                   "\\valid(dest[1])",0,__gen_e_acsl_valid_4);
      __gen_e_acsl_and_4 = __gen_e_acsl_valid_4;
    }
    else __gen_e_acsl_and_4 = 0;
    __gen_e_acsl_assert_data_4.blocking = 1;
    __gen_e_acsl_assert_data_4.kind = "Assertion";
    __gen_e_acsl_assert_data_4.pred_txt = "\\valid(dest[1])";
    __gen_e_acsl_assert_data_4.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_4.fct = "main";
    __gen_e_acsl_assert_data_4.line = 26;
    __e_acsl_assert(__gen_e_acsl_and_4,& __gen_e_acsl_assert_data_4);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_4);
  }
  /*@ assert \valid(dest[1]); */ ;
  __e_acsl_temporal_reset_parameters();
  __e_acsl_temporal_reset_return();
  __e_acsl_temporal_save_nblock_parameter((void *)(& dest),0U);
  __gen_e_acsl_memset((void *)(& dest),0,(size_t)size);
  {
    int __gen_e_acsl_initialized_5;
    int __gen_e_acsl_and_5;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_5 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_5 = __e_acsl_initialized((void *)(dest),
                                                      sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_5,"(int **)dest",
                                 (void *)(dest));
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_5,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_5,
                                 "\\initialized((int **)dest)",0,
                                 __gen_e_acsl_initialized_5);
    if (__gen_e_acsl_initialized_5) {
      int __gen_e_acsl_valid_5;
      __gen_e_acsl_valid_5 = __e_acsl_valid((void *)dest[0],sizeof(int),
                                            (void *)dest[0],(void *)(dest));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_5,"dest[0]",
                                   (void *)dest[0]);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_5,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_5,
                                   "\\valid(dest[0])",0,__gen_e_acsl_valid_5);
      __gen_e_acsl_and_5 = __gen_e_acsl_valid_5;
    }
    else __gen_e_acsl_and_5 = 0;
    __gen_e_acsl_assert_data_5.blocking = 1;
    __gen_e_acsl_assert_data_5.kind = "Assertion";
    __gen_e_acsl_assert_data_5.pred_txt = "!\\valid(dest[0])";
    __gen_e_acsl_assert_data_5.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_5.fct = "main";
    __gen_e_acsl_assert_data_5.line = 30;
    __e_acsl_assert(! __gen_e_acsl_and_5,& __gen_e_acsl_assert_data_5);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_5);
  }
  /*@ assert !\valid(dest[0]); */ ;
  {
    int __gen_e_acsl_initialized_6;
    int __gen_e_acsl_and_6;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_6 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_6 = __e_acsl_initialized((void *)(& dest[1]),
                                                      sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_6,"&dest[1]",
                                 (void *)(& dest[1]));
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_6,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_6,
                                 "\\initialized(&dest[1])",0,
                                 __gen_e_acsl_initialized_6);
    if (__gen_e_acsl_initialized_6) {
      int __gen_e_acsl_valid_6;
      __gen_e_acsl_valid_6 = __e_acsl_valid((void *)dest[1],sizeof(int),
                                            (void *)dest[1],
                                            (void *)(& dest[1]));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_6,"dest[1]",
                                   (void *)dest[1]);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_6,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_6,
                                   "\\valid(dest[1])",0,__gen_e_acsl_valid_6);
      __gen_e_acsl_and_6 = __gen_e_acsl_valid_6;
    }
    else __gen_e_acsl_and_6 = 0;
    __gen_e_acsl_assert_data_6.blocking = 1;
    __gen_e_acsl_assert_data_6.kind = "Assertion";
    __gen_e_acsl_assert_data_6.pred_txt = "!\\valid(dest[1])";
    __gen_e_acsl_assert_data_6.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_6.fct = "main";
    __gen_e_acsl_assert_data_6.line = 31;
    __e_acsl_assert(! __gen_e_acsl_and_6,& __gen_e_acsl_assert_data_6);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_6);
  }
  /*@ assert !\valid(dest[1]); */ ;
  __e_acsl_temporal_reset_parameters();
  __e_acsl_temporal_reset_return();
  int **p = malloc((size_t)size);
  __e_acsl_temporal_store_nblock((void *)(& p),(void *)*(& p));
  __e_acsl_store_block((void *)(& p),8UL);
  __e_acsl_full_init((void *)(& p));
  __e_acsl_temporal_reset_parameters();
  __e_acsl_temporal_reset_return();
  int **q = malloc((size_t)size);
  __e_acsl_temporal_store_nblock((void *)(& q),(void *)*(& q));
  __e_acsl_store_block((void *)(& q),8UL);
  __e_acsl_full_init((void *)(& q));
  __e_acsl_initialize((void *)p,sizeof(int *));
  __e_acsl_temporal_store_nblock((void *)p,(void *)(& a));
  *p = & a;
  __e_acsl_initialize((void *)(p + 1),sizeof(int *));
  __e_acsl_temporal_store_nblock((void *)(p + 1),(void *)(& a));
  *(p + 1) = & a;
  {
    int __gen_e_acsl_initialized_7;
    int __gen_e_acsl_and_8;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_7 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_7 = __e_acsl_initialized((void *)p,
                                                      sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_7,"p",(void *)p);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_7,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_7,
                                 "\\initialized(p)",0,
                                 __gen_e_acsl_initialized_7);
    if (__gen_e_acsl_initialized_7) {
      int __gen_e_acsl_initialized_8;
      int __gen_e_acsl_and_7;
      int __gen_e_acsl_valid_7;
      __e_acsl_assert_data_t __gen_e_acsl_assert_data_8 =
        {.values = (void *)0};
      __gen_e_acsl_initialized_8 = __e_acsl_initialized((void *)(& p),
                                                        sizeof(int **));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_8,"&p",
                                   (void *)(& p));
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_8,
                                     "sizeof(int **)",0,sizeof(int **));
      if (__gen_e_acsl_initialized_8) {
        int __gen_e_acsl_valid_read;
        __gen_e_acsl_valid_read = __e_acsl_valid_read((void *)p,
                                                      sizeof(int *),
                                                      (void *)p,
                                                      (void *)(& p));
        __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_8,"p",
                                     (void *)p);
        __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_8,
                                       "sizeof(int *)",0,sizeof(int *));
        __gen_e_acsl_and_7 = __gen_e_acsl_valid_read;
      }
      else __gen_e_acsl_and_7 = 0;
      __gen_e_acsl_assert_data_8.blocking = 1;
      __gen_e_acsl_assert_data_8.kind = "RTE";
      __gen_e_acsl_assert_data_8.pred_txt = "\\valid_read(p)";
      __gen_e_acsl_assert_data_8.file = "t_memcpy.c";
      __gen_e_acsl_assert_data_8.fct = "main";
      __gen_e_acsl_assert_data_8.line = 40;
      __gen_e_acsl_assert_data_8.name = "mem_access";
      __e_acsl_assert(__gen_e_acsl_and_7,& __gen_e_acsl_assert_data_8);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_8);
      __gen_e_acsl_valid_7 = __e_acsl_valid((void *)*p,sizeof(int),
                                            (void *)*p,(void *)p);
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_7,"*p",
                                   (void *)*p);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_7,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_7,
                                   "\\valid(*p)",0,__gen_e_acsl_valid_7);
      __gen_e_acsl_and_8 = __gen_e_acsl_valid_7;
    }
    else __gen_e_acsl_and_8 = 0;
    __gen_e_acsl_assert_data_7.blocking = 1;
    __gen_e_acsl_assert_data_7.kind = "Assertion";
    __gen_e_acsl_assert_data_7.pred_txt = "\\valid(*p)";
    __gen_e_acsl_assert_data_7.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_7.fct = "main";
    __gen_e_acsl_assert_data_7.line = 40;
    __e_acsl_assert(__gen_e_acsl_and_8,& __gen_e_acsl_assert_data_7);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_7);
  }
  /*@ assert \valid(*p); */ ;
  {
    int __gen_e_acsl_initialized_9;
    int __gen_e_acsl_and_9;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_9 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_9 = __e_acsl_initialized((void *)(p + 1),
                                                      sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_9,"p",(void *)p);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_9,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_9,
                                 "\\initialized(p + 1)",0,
                                 __gen_e_acsl_initialized_9);
    if (__gen_e_acsl_initialized_9) {
      int __gen_e_acsl_valid_read_2;
      int __gen_e_acsl_valid_8;
      __e_acsl_assert_data_t __gen_e_acsl_assert_data_10 =
        {.values = (void *)0};
      __gen_e_acsl_valid_read_2 = __e_acsl_valid_read((void *)(p + 1),
                                                      sizeof(int *),
                                                      (void *)p,
                                                      (void *)(& p));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_10,"p",
                                   (void *)p);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_10,
                                     "sizeof(int *)",0,sizeof(int *));
      __gen_e_acsl_assert_data_10.blocking = 1;
      __gen_e_acsl_assert_data_10.kind = "RTE";
      __gen_e_acsl_assert_data_10.pred_txt = "\\valid_read(p + 1)";
      __gen_e_acsl_assert_data_10.file = "t_memcpy.c";
      __gen_e_acsl_assert_data_10.fct = "main";
      __gen_e_acsl_assert_data_10.line = 41;
      __gen_e_acsl_assert_data_10.name = "mem_access";
      __e_acsl_assert(__gen_e_acsl_valid_read_2,
                      & __gen_e_acsl_assert_data_10);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_10);
      __gen_e_acsl_valid_8 = __e_acsl_valid((void *)*(p + 1),sizeof(int),
                                            (void *)*(p + 1),(void *)(
                                            p + 1));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_9,"*(p + 1)",
                                   (void *)*(p + 1));
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_9,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_9,
                                   "\\valid(*(p + 1))",0,
                                   __gen_e_acsl_valid_8);
      __gen_e_acsl_and_9 = __gen_e_acsl_valid_8;
    }
    else __gen_e_acsl_and_9 = 0;
    __gen_e_acsl_assert_data_9.blocking = 1;
    __gen_e_acsl_assert_data_9.kind = "Assertion";
    __gen_e_acsl_assert_data_9.pred_txt = "\\valid(*(p + 1))";
    __gen_e_acsl_assert_data_9.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_9.fct = "main";
    __gen_e_acsl_assert_data_9.line = 41;
    __e_acsl_assert(__gen_e_acsl_and_9,& __gen_e_acsl_assert_data_9);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_9);
  }
  /*@ assert \valid(*(p + 1)); */ ;
  {
    int __gen_e_acsl_initialized_10;
    int __gen_e_acsl_and_11;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_11 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_10 = __e_acsl_initialized((void *)q,
                                                       sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_11,"q",(void *)q);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_11,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_11,
                                 "\\initialized(q)",0,
                                 __gen_e_acsl_initialized_10);
    if (__gen_e_acsl_initialized_10) {
      int __gen_e_acsl_initialized_11;
      int __gen_e_acsl_and_10;
      int __gen_e_acsl_valid_9;
      __e_acsl_assert_data_t __gen_e_acsl_assert_data_12 =
        {.values = (void *)0};
      __gen_e_acsl_initialized_11 = __e_acsl_initialized((void *)(& q),
                                                         sizeof(int **));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_12,"&q",
                                   (void *)(& q));
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_12,
                                     "sizeof(int **)",0,sizeof(int **));
      if (__gen_e_acsl_initialized_11) {
        int __gen_e_acsl_valid_read_3;
        __gen_e_acsl_valid_read_3 = __e_acsl_valid_read((void *)q,
                                                        sizeof(int *),
                                                        (void *)q,
                                                        (void *)(& q));
        __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_12,"q",
                                     (void *)q);
        __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_12,
                                       "sizeof(int *)",0,sizeof(int *));
        __gen_e_acsl_and_10 = __gen_e_acsl_valid_read_3;
      }
      else __gen_e_acsl_and_10 = 0;
      __gen_e_acsl_assert_data_12.blocking = 1;
      __gen_e_acsl_assert_data_12.kind = "RTE";
      __gen_e_acsl_assert_data_12.pred_txt = "\\valid_read(q)";
      __gen_e_acsl_assert_data_12.file = "t_memcpy.c";
      __gen_e_acsl_assert_data_12.fct = "main";
      __gen_e_acsl_assert_data_12.line = 42;
      __gen_e_acsl_assert_data_12.name = "mem_access";
      __e_acsl_assert(__gen_e_acsl_and_10,& __gen_e_acsl_assert_data_12);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_12);
      __gen_e_acsl_valid_9 = __e_acsl_valid((void *)*q,sizeof(int),
                                            (void *)*q,(void *)q);
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_11,"*q",
                                   (void *)*q);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_11,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_11,
                                   "\\valid(*q)",0,__gen_e_acsl_valid_9);
      __gen_e_acsl_and_11 = __gen_e_acsl_valid_9;
    }
    else __gen_e_acsl_and_11 = 0;
    __gen_e_acsl_assert_data_11.blocking = 1;
    __gen_e_acsl_assert_data_11.kind = "Assertion";
    __gen_e_acsl_assert_data_11.pred_txt = "!\\valid(*q)";
    __gen_e_acsl_assert_data_11.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_11.fct = "main";
    __gen_e_acsl_assert_data_11.line = 42;
    __e_acsl_assert(! __gen_e_acsl_and_11,& __gen_e_acsl_assert_data_11);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_11);
  }
  /*@ assert !\valid(*q); */ ;
  {
    int __gen_e_acsl_initialized_12;
    int __gen_e_acsl_and_12;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_13 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_12 = __e_acsl_initialized((void *)(q + 1),
                                                       sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_13,"q",(void *)q);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_13,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_13,
                                 "\\initialized(q + 1)",0,
                                 __gen_e_acsl_initialized_12);
    if (__gen_e_acsl_initialized_12) {
      int __gen_e_acsl_valid_read_4;
      int __gen_e_acsl_valid_10;
      __e_acsl_assert_data_t __gen_e_acsl_assert_data_14 =
        {.values = (void *)0};
      __gen_e_acsl_valid_read_4 = __e_acsl_valid_read((void *)(q + 1),
                                                      sizeof(int *),
                                                      (void *)q,
                                                      (void *)(& q));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_14,"q",
                                   (void *)q);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_14,
                                     "sizeof(int *)",0,sizeof(int *));
      __gen_e_acsl_assert_data_14.blocking = 1;
      __gen_e_acsl_assert_data_14.kind = "RTE";
      __gen_e_acsl_assert_data_14.pred_txt = "\\valid_read(q + 1)";
      __gen_e_acsl_assert_data_14.file = "t_memcpy.c";
      __gen_e_acsl_assert_data_14.fct = "main";
      __gen_e_acsl_assert_data_14.line = 43;
      __gen_e_acsl_assert_data_14.name = "mem_access";
      __e_acsl_assert(__gen_e_acsl_valid_read_4,
                      & __gen_e_acsl_assert_data_14);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_14);
      __gen_e_acsl_valid_10 = __e_acsl_valid((void *)*(q + 1),sizeof(int),
                                             (void *)*(q + 1),
                                             (void *)(q + 1));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_13,"*(q + 1)",
                                   (void *)*(q + 1));
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_13,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_13,
                                   "\\valid(*(q + 1))",0,
                                   __gen_e_acsl_valid_10);
      __gen_e_acsl_and_12 = __gen_e_acsl_valid_10;
    }
    else __gen_e_acsl_and_12 = 0;
    __gen_e_acsl_assert_data_13.blocking = 1;
    __gen_e_acsl_assert_data_13.kind = "Assertion";
    __gen_e_acsl_assert_data_13.pred_txt = "!\\valid(*(q + 1))";
    __gen_e_acsl_assert_data_13.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_13.fct = "main";
    __gen_e_acsl_assert_data_13.line = 43;
    __e_acsl_assert(! __gen_e_acsl_and_12,& __gen_e_acsl_assert_data_13);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_13);
  }
  /*@ assert !\valid(*(q + 1)); */ ;
  __e_acsl_full_init((void *)(& tmp_1));
  __e_acsl_temporal_store_nblock((void *)(& tmp_1),(void *)0);
  tmp_1 = (int *)0;
  __e_acsl_initialize((void *)(q + 1),sizeof(int *));
  __e_acsl_temporal_store_nreferent((void *)(q + 1),(void *)(& tmp_1));
  *(q + 1) = tmp_1;
  __e_acsl_initialize((void *)q,sizeof(int *));
  __e_acsl_temporal_store_nreferent((void *)q,(void *)(& tmp_1));
  *q = tmp_1;
  __e_acsl_temporal_reset_parameters();
  __e_acsl_temporal_reset_return();
  __e_acsl_temporal_save_nreferent_parameter((void *)(& q),0U);
  __e_acsl_temporal_save_nreferent_parameter((void *)(& p),1U);
  __gen_e_acsl_memcpy((void *)q,(void const *)p,(size_t)size);
  {
    int __gen_e_acsl_initialized_13;
    int __gen_e_acsl_and_14;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_15 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_13 = __e_acsl_initialized((void *)q,
                                                       sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_15,"q",(void *)q);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_15,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_15,
                                 "\\initialized(q)",0,
                                 __gen_e_acsl_initialized_13);
    if (__gen_e_acsl_initialized_13) {
      int __gen_e_acsl_initialized_14;
      int __gen_e_acsl_and_13;
      int __gen_e_acsl_valid_11;
      __e_acsl_assert_data_t __gen_e_acsl_assert_data_16 =
        {.values = (void *)0};
      __gen_e_acsl_initialized_14 = __e_acsl_initialized((void *)(& q),
                                                         sizeof(int **));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_16,"&q",
                                   (void *)(& q));
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_16,
                                     "sizeof(int **)",0,sizeof(int **));
      if (__gen_e_acsl_initialized_14) {
        int __gen_e_acsl_valid_read_5;
        __gen_e_acsl_valid_read_5 = __e_acsl_valid_read((void *)q,
                                                        sizeof(int *),
                                                        (void *)q,
                                                        (void *)(& q));
        __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_16,"q",
                                     (void *)q);
        __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_16,
                                       "sizeof(int *)",0,sizeof(int *));
        __gen_e_acsl_and_13 = __gen_e_acsl_valid_read_5;
      }
      else __gen_e_acsl_and_13 = 0;
      __gen_e_acsl_assert_data_16.blocking = 1;
      __gen_e_acsl_assert_data_16.kind = "RTE";
      __gen_e_acsl_assert_data_16.pred_txt = "\\valid_read(q)";
      __gen_e_acsl_assert_data_16.file = "t_memcpy.c";
      __gen_e_acsl_assert_data_16.fct = "main";
      __gen_e_acsl_assert_data_16.line = 48;
      __gen_e_acsl_assert_data_16.name = "mem_access";
      __e_acsl_assert(__gen_e_acsl_and_13,& __gen_e_acsl_assert_data_16);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_16);
      __gen_e_acsl_valid_11 = __e_acsl_valid((void *)*q,sizeof(int),
                                             (void *)*q,(void *)q);
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_15,"*q",
                                   (void *)*q);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_15,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_15,
                                   "\\valid(*q)",0,__gen_e_acsl_valid_11);
      __gen_e_acsl_and_14 = __gen_e_acsl_valid_11;
    }
    else __gen_e_acsl_and_14 = 0;
    __gen_e_acsl_assert_data_15.blocking = 1;
    __gen_e_acsl_assert_data_15.kind = "Assertion";
    __gen_e_acsl_assert_data_15.pred_txt = "\\valid(*q)";
    __gen_e_acsl_assert_data_15.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_15.fct = "main";
    __gen_e_acsl_assert_data_15.line = 48;
    __e_acsl_assert(__gen_e_acsl_and_14,& __gen_e_acsl_assert_data_15);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_15);
  }
  /*@ assert \valid(*q); */ ;
  {
    int __gen_e_acsl_initialized_15;
    int __gen_e_acsl_and_15;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_17 =
      {.values = (void *)0};
    __gen_e_acsl_initialized_15 = __e_acsl_initialized((void *)(q + 1),
                                                       sizeof(int *));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_17,"q",(void *)q);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_17,
                                   "sizeof(int *)",0,sizeof(int *));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_17,
                                 "\\initialized(q + 1)",0,
                                 __gen_e_acsl_initialized_15);
    if (__gen_e_acsl_initialized_15) {
      int __gen_e_acsl_valid_read_6;
      int __gen_e_acsl_valid_12;
      __e_acsl_assert_data_t __gen_e_acsl_assert_data_18 =
        {.values = (void *)0};
      __gen_e_acsl_valid_read_6 = __e_acsl_valid_read((void *)(q + 1),
                                                      sizeof(int *),
                                                      (void *)q,
                                                      (void *)(& q));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_18,"q",
                                   (void *)q);
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_18,
                                     "sizeof(int *)",0,sizeof(int *));
      __gen_e_acsl_assert_data_18.blocking = 1;
      __gen_e_acsl_assert_data_18.kind = "RTE";
      __gen_e_acsl_assert_data_18.pred_txt = "\\valid_read(q + 1)";
      __gen_e_acsl_assert_data_18.file = "t_memcpy.c";
      __gen_e_acsl_assert_data_18.fct = "main";
      __gen_e_acsl_assert_data_18.line = 49;
      __gen_e_acsl_assert_data_18.name = "mem_access";
      __e_acsl_assert(__gen_e_acsl_valid_read_6,
                      & __gen_e_acsl_assert_data_18);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_18);
      __gen_e_acsl_valid_12 = __e_acsl_valid((void *)*(q + 1),sizeof(int),
                                             (void *)*(q + 1),
                                             (void *)(q + 1));
      __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_17,"*(q + 1)",
                                   (void *)*(q + 1));
      __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_17,
                                     "sizeof(int)",0,sizeof(int));
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_17,
                                   "\\valid(*(q + 1))",0,
                                   __gen_e_acsl_valid_12);
      __gen_e_acsl_and_15 = __gen_e_acsl_valid_12;
    }
    else __gen_e_acsl_and_15 = 0;
    __gen_e_acsl_assert_data_17.blocking = 1;
    __gen_e_acsl_assert_data_17.kind = "Assertion";
    __gen_e_acsl_assert_data_17.pred_txt = "\\valid(*(q + 1))";
    __gen_e_acsl_assert_data_17.file = "t_memcpy.c";
    __gen_e_acsl_assert_data_17.fct = "main";
    __gen_e_acsl_assert_data_17.line = 49;
    __e_acsl_assert(__gen_e_acsl_and_15,& __gen_e_acsl_assert_data_17);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_17);
  }
  /*@ assert \valid(*(q + 1)); */ ;
  __retres = 0;
  __e_acsl_delete_block((void *)(& tmp_1));
  __e_acsl_delete_block((void *)(& q));
  __e_acsl_delete_block((void *)(& p));
  __e_acsl_delete_block((void *)(dest));
  __e_acsl_delete_block((void *)(src));
  __e_acsl_delete_block((void *)(& b));
  __e_acsl_delete_block((void *)(& a));
  __e_acsl_memory_clean();
  return __retres;
}

/*@ requires valid_s: valid_or_empty(s, n);
    ensures acsl_c_equiv: memset((char *)\old(s), \old(c), \old(n)) == \true;
    ensures result_ptr: \result == \old(s);
    assigns *((char *)s + (0 .. n - 1)), \result;
    assigns *((char *)s + (0 .. n - 1)) \from c;
    assigns \result \from s;
 */
void *__gen_e_acsl_memset(void *s, int c, size_t n)
{
  void *__gen_e_acsl_at_4;
  int __gen_e_acsl_at_3;
  size_t __gen_e_acsl_at_2;
  void *__gen_e_acsl_at;
  void *__retres;
  {
    int __gen_e_acsl_valid_or_empty_here_2;
    __e_acsl_store_block((void *)(& s),8UL);
    __e_acsl_temporal_pull_parameter((void *)(& s),0U,8UL);
    __gen_e_acsl_at = s;
    __gen_e_acsl_at_2 = n;
    __gen_e_acsl_at_3 = c;
    __gen_e_acsl_at_4 = s;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __gen_e_acsl_valid_or_empty_here_2 = __gen_e_acsl_valid_or_empty_here
    (s,n);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data,"n",0,n);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data,"s",s);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,
                                 "valid_s: valid_or_empty(s, n)",0,
                                 __gen_e_acsl_valid_or_empty_here_2);
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Precondition";
    __gen_e_acsl_assert_data.pred_txt = "valid_or_empty(s, n)";
    __gen_e_acsl_assert_data.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data.fct = "memset";
    __gen_e_acsl_assert_data.line = 164;
    __gen_e_acsl_assert_data.name = "valid_s";
    __e_acsl_assert(__gen_e_acsl_valid_or_empty_here_2,
                    & __gen_e_acsl_assert_data);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data);
    __e_acsl_temporal_reset_parameters();
    __e_acsl_temporal_reset_return();
    __e_acsl_temporal_save_nreferent_parameter((void *)(& s),0U);
    __e_acsl_temporal_memset(s,c,n);
  }
  __retres = memset(s,c,n);
  __e_acsl_initialize(s,n);
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_3 =
      {.values = (void *)0};
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_3,"\\result",
                                 __retres);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_3,"\\old(s)",
                                 __gen_e_acsl_at);
    __gen_e_acsl_assert_data_3.blocking = 1;
    __gen_e_acsl_assert_data_3.kind = "Postcondition";
    __gen_e_acsl_assert_data_3.pred_txt = "\\result == \\old(s)";
    __gen_e_acsl_assert_data_3.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data_3.fct = "memset";
    __gen_e_acsl_assert_data_3.line = 168;
    __gen_e_acsl_assert_data_3.name = "result_ptr";
    __e_acsl_assert(__retres == __gen_e_acsl_at,& __gen_e_acsl_assert_data_3);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_3);
    __e_acsl_delete_block((void *)(& s));
    return __retres;
  }
}

/*@ requires valid_dest: valid_or_empty(dest, n);
    requires valid_src: valid_read_or_empty(src, n);
    requires
      separation:
        \separated((char *)dest + (0 .. n - 1), (char *)src + (0 .. n - 1));
    ensures
      copied_contents:
        memcmp{Post, Pre}((char *)\old(dest), (char *)\old(src), \old(n)) ==
        0;
    ensures result_ptr: \result == \old(dest);
    assigns *((char *)dest + (0 .. n - 1)), \result;
    assigns *((char *)dest + (0 .. n - 1))
      \from *((char *)src + (0 .. n - 1));
    assigns \result \from dest;
 */
void *__gen_e_acsl_memcpy(void * restrict dest, void const * restrict src,
                          size_t n)
{
  void *__gen_e_acsl_at;
  void *__retres;
  {
    int __gen_e_acsl_valid_or_empty_here_3;
    int __gen_e_acsl_valid_read_or_empty_here_2;
    unsigned long __gen_e_acsl_size_3;
    __e_acsl_mpz_t __gen_e_acsl_n_2;
    __e_acsl_mpz_t __gen_e_acsl__5;
    __e_acsl_mpz_t __gen_e_acsl_sub_3;
    __e_acsl_mpz_t __gen_e_acsl__6;
    __e_acsl_mpz_t __gen_e_acsl_sub_4;
    __e_acsl_mpz_t __gen_e_acsl_add_2;
    unsigned long __gen_e_acsl_add_3;
    unsigned long __gen_e_acsl_if_2;
    int __gen_e_acsl_valid_read_3;
    unsigned long __gen_e_acsl_size_4;
    unsigned long __gen_e_acsl_add_4;
    unsigned long __gen_e_acsl_if_3;
    int __gen_e_acsl_valid_read_4;
    unsigned long __gen_e_acsl_size_5;
    unsigned long __gen_e_acsl_add_5;
    unsigned long __gen_e_acsl_if_4;
    unsigned long __gen_e_acsl_size_6;
    unsigned long __gen_e_acsl_add_6;
    unsigned long __gen_e_acsl_if_5;
    int __gen_e_acsl_separated;
    __e_acsl_store_block((void *)(& src),8UL);
    __e_acsl_store_block((void *)(& dest),8UL);
    __e_acsl_temporal_pull_parameter((void *)(& dest),0U,8UL);
    __e_acsl_temporal_pull_parameter((void *)(& src),1U,8UL);
    __gen_e_acsl_at = dest;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __gen_e_acsl_valid_or_empty_here_3 = __gen_e_acsl_valid_or_empty_here
    (dest,n);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data,"n",0,n);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data,"dest",dest);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,
                                 "valid_dest: valid_or_empty(dest, n)",0,
                                 __gen_e_acsl_valid_or_empty_here_3);
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Precondition";
    __gen_e_acsl_assert_data.pred_txt = "valid_or_empty(dest, n)";
    __gen_e_acsl_assert_data.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data.fct = "memcpy";
    __gen_e_acsl_assert_data.line = 128;
    __gen_e_acsl_assert_data.name = "valid_dest";
    __e_acsl_assert(__gen_e_acsl_valid_or_empty_here_3,
                    & __gen_e_acsl_assert_data);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data);
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_2 =
      {.values = (void *)0};
    __gen_e_acsl_valid_read_or_empty_here_2 = __gen_e_acsl_valid_read_or_empty_here
    ((void *)src,n);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_2,"n",0,n);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_2,"src",
                                 (void *)src);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_2,
                                 "valid_src: valid_read_or_empty(src, n)",0,
                                 __gen_e_acsl_valid_read_or_empty_here_2);
    __gen_e_acsl_assert_data_2.blocking = 1;
    __gen_e_acsl_assert_data_2.kind = "Precondition";
    __gen_e_acsl_assert_data_2.pred_txt = "valid_read_or_empty(src, n)";
    __gen_e_acsl_assert_data_2.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data_2.fct = "memcpy";
    __gen_e_acsl_assert_data_2.line = 129;
    __gen_e_acsl_assert_data_2.name = "valid_src";
    __e_acsl_assert(__gen_e_acsl_valid_read_or_empty_here_2,
                    & __gen_e_acsl_assert_data_2);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_2);
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_4 =
      {.values = (void *)0};
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_5 =
      {.values = (void *)0};
    __gmpz_init_set_ui(__gen_e_acsl_n_2,n);
    __gmpz_init_set_si(__gen_e_acsl__5,1L);
    __gmpz_init(__gen_e_acsl_sub_3);
    __gmpz_sub(__gen_e_acsl_sub_3,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_2),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__5));
    __gmpz_init_set_si(__gen_e_acsl__6,0L);
    __gmpz_init(__gen_e_acsl_sub_4);
    __gmpz_sub(__gen_e_acsl_sub_4,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_sub_3),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__6));
    __gmpz_init(__gen_e_acsl_add_2);
    __gmpz_add(__gen_e_acsl_add_2,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_sub_4),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__5));
    __gen_e_acsl_add_3 = __gmpz_get_ui((__e_acsl_mpz_struct const *)(__gen_e_acsl_add_2));
    __gen_e_acsl_size_3 = 1UL * __gen_e_acsl_add_3;
    if (__gen_e_acsl_size_3 <= 0UL) __gen_e_acsl_if_2 = 0UL;
    else __gen_e_acsl_if_2 = __gen_e_acsl_size_3;
    __gen_e_acsl_valid_read_3 = __e_acsl_valid_read((void *)((char *)dest + 
                                                             1 * 0),
                                                    __gen_e_acsl_if_2,dest,
                                                    (void *)(& dest));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_5,"dest",dest);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_5,"sizeof(char)",
                                 0,1);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_5,"sizeof(char)",
                                 0,1);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_5,"n",0,n);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_5,"size",0,
                                   __gen_e_acsl_size_3);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_5,"size",0,
                                   __gen_e_acsl_size_3);
    __gen_e_acsl_assert_data_5.blocking = 1;
    __gen_e_acsl_assert_data_5.kind = "RTE";
    __gen_e_acsl_assert_data_5.pred_txt = "\\valid_read((char *)dest + (0 .. n - 1))";
    __gen_e_acsl_assert_data_5.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data_5.fct = "memcpy";
    __gen_e_acsl_assert_data_5.line = 131;
    __gen_e_acsl_assert_data_5.name = "separated_guard";
    __e_acsl_assert(__gen_e_acsl_valid_read_3,& __gen_e_acsl_assert_data_5);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_5);
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_6 =
      {.values = (void *)0};
    __gen_e_acsl_add_4 = __gmpz_get_ui((__e_acsl_mpz_struct const *)(__gen_e_acsl_add_2));
    __gen_e_acsl_size_4 = 1UL * __gen_e_acsl_add_4;
    if (__gen_e_acsl_size_4 <= 0UL) __gen_e_acsl_if_3 = 0UL;
    else __gen_e_acsl_if_3 = __gen_e_acsl_size_4;
    __gen_e_acsl_valid_read_4 = __e_acsl_valid_read((void *)((char *)src + 
                                                             1 * 0),
                                                    __gen_e_acsl_if_3,
                                                    (void *)src,
                                                    (void *)(& src));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_6,"src",
                                 (void *)src);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_6,"sizeof(char)",
                                 0,1);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_6,"sizeof(char)",
                                 0,1);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_6,"n",0,n);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_6,"size",0,
                                   __gen_e_acsl_size_4);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_6,"size",0,
                                   __gen_e_acsl_size_4);
    __gen_e_acsl_assert_data_6.blocking = 1;
    __gen_e_acsl_assert_data_6.kind = "RTE";
    __gen_e_acsl_assert_data_6.pred_txt = "\\valid_read((char *)src + (0 .. n - 1))";
    __gen_e_acsl_assert_data_6.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data_6.fct = "memcpy";
    __gen_e_acsl_assert_data_6.line = 131;
    __gen_e_acsl_assert_data_6.name = "separated_guard";
    __e_acsl_assert(__gen_e_acsl_valid_read_4,& __gen_e_acsl_assert_data_6);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_6);
    __gen_e_acsl_add_5 = __gmpz_get_ui((__e_acsl_mpz_struct const *)(__gen_e_acsl_add_2));
    __gen_e_acsl_size_5 = 1UL * __gen_e_acsl_add_5;
    if (__gen_e_acsl_size_5 <= 0UL) __gen_e_acsl_if_4 = 0UL;
    else __gen_e_acsl_if_4 = __gen_e_acsl_size_5;
    __gen_e_acsl_add_6 = __gmpz_get_ui((__e_acsl_mpz_struct const *)(__gen_e_acsl_add_2));
    __gen_e_acsl_size_6 = 1UL * __gen_e_acsl_add_6;
    if (__gen_e_acsl_size_6 <= 0UL) __gen_e_acsl_if_5 = 0UL;
    else __gen_e_acsl_if_5 = __gen_e_acsl_size_6;
    __gen_e_acsl_separated = __e_acsl_separated(2UL,(char *)dest + 1 * 0,
                                                __gen_e_acsl_if_4,
                                                (char *)src + 1 * 0,
                                                __gen_e_acsl_if_5);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_4,"dest",dest);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,"sizeof(char)",
                                 0,1);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,"sizeof(char)",
                                 0,1);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,"n",0,n);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,"size",0,
                                   __gen_e_acsl_size_5);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,"size",0,
                                   __gen_e_acsl_size_5);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_4,"src",
                                 (void *)src);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,"sizeof(char)",
                                 0,1);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,"sizeof(char)",
                                 0,1);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,"n",0,n);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,"size",0,
                                   __gen_e_acsl_size_6);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,"size",0,
                                   __gen_e_acsl_size_6);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,
                                 "separation:\n  \\separated((char *)dest + (0 .. n - 1), (char *)src + (0 .. n - 1))",
                                 0,__gen_e_acsl_separated);
    __gen_e_acsl_assert_data_4.blocking = 1;
    __gen_e_acsl_assert_data_4.kind = "Precondition";
    __gen_e_acsl_assert_data_4.pred_txt = "\\separated((char *)dest + (0 .. n - 1), (char *)src + (0 .. n - 1))";
    __gen_e_acsl_assert_data_4.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data_4.fct = "memcpy";
    __gen_e_acsl_assert_data_4.line = 131;
    __gen_e_acsl_assert_data_4.name = "separation";
    __e_acsl_assert(__gen_e_acsl_separated,& __gen_e_acsl_assert_data_4);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_4);
    __e_acsl_temporal_reset_parameters();
    __e_acsl_temporal_reset_return();
    __e_acsl_temporal_save_nreferent_parameter((void *)(& dest),0U);
    __e_acsl_temporal_save_nreferent_parameter((void *)(& src),1U);
    __e_acsl_temporal_memcpy(dest,(void *)src,n);
    __gmpz_clear(__gen_e_acsl_n_2);
    __gmpz_clear(__gen_e_acsl__5);
    __gmpz_clear(__gen_e_acsl_sub_3);
    __gmpz_clear(__gen_e_acsl__6);
    __gmpz_clear(__gen_e_acsl_sub_4);
    __gmpz_clear(__gen_e_acsl_add_2);
  }
  __retres = memcpy(dest,src,n);
  __e_acsl_initialize(dest,n);
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_8 =
      {.values = (void *)0};
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_8,"\\result",
                                 __retres);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_8,"\\old(dest)",
                                 __gen_e_acsl_at);
    __gen_e_acsl_assert_data_8.blocking = 1;
    __gen_e_acsl_assert_data_8.kind = "Postcondition";
    __gen_e_acsl_assert_data_8.pred_txt = "\\result == \\old(dest)";
    __gen_e_acsl_assert_data_8.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data_8.fct = "memcpy";
    __gen_e_acsl_assert_data_8.line = 135;
    __gen_e_acsl_assert_data_8.name = "result_ptr";
    __e_acsl_assert(__retres == __gen_e_acsl_at,& __gen_e_acsl_assert_data_8);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_8);
    __e_acsl_delete_block((void *)(& src));
    __e_acsl_delete_block((void *)(& dest));
    return __retres;
  }
}

int __gen_e_acsl_valid_or_empty_here(void *s, unsigned long n)
{
  int __gen_e_acsl_empty_block_here_2;
  int __gen_e_acsl_or;
  int __gen_e_acsl_and_2;
  __gen_e_acsl_empty_block_here_2 = __gen_e_acsl_empty_block_here(s);
  if (__gen_e_acsl_empty_block_here_2) __gen_e_acsl_or = 1;
  else {
    int __gen_e_acsl_valid_read;
    __gen_e_acsl_valid_read = __e_acsl_valid_read(s,sizeof(char),s,
                                                  (void *)(& s));
    __gen_e_acsl_or = __gen_e_acsl_valid_read;
  }
  if (__gen_e_acsl_or) {
    unsigned long __gen_e_acsl_size;
    __e_acsl_mpz_t __gen_e_acsl_n;
    __e_acsl_mpz_t __gen_e_acsl_;
    __e_acsl_mpz_t __gen_e_acsl_sub;
    __e_acsl_mpz_t __gen_e_acsl__2;
    __e_acsl_mpz_t __gen_e_acsl_sub_2;
    __e_acsl_mpz_t __gen_e_acsl_add;
    unsigned long __gen_e_acsl_add_2;
    unsigned long __gen_e_acsl_if;
    int __gen_e_acsl_valid;
    __gmpz_init_set_ui(__gen_e_acsl_n,n);
    __gmpz_init_set_si(__gen_e_acsl_,1L);
    __gmpz_init(__gen_e_acsl_sub);
    __gmpz_sub(__gen_e_acsl_sub,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_));
    __gmpz_init_set_si(__gen_e_acsl__2,0L);
    __gmpz_init(__gen_e_acsl_sub_2);
    __gmpz_sub(__gen_e_acsl_sub_2,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_sub),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__2));
    __gmpz_init(__gen_e_acsl_add);
    __gmpz_add(__gen_e_acsl_add,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_sub_2),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_));
    __gen_e_acsl_add_2 = __gmpz_get_ui((__e_acsl_mpz_struct const *)(__gen_e_acsl_add));
    __gen_e_acsl_size = 1UL * __gen_e_acsl_add_2;
    if (__gen_e_acsl_size <= 0UL) __gen_e_acsl_if = 0UL;
    else __gen_e_acsl_if = __gen_e_acsl_size;
    __gen_e_acsl_valid = __e_acsl_valid((void *)((char *)s + 1 * 0),
                                        __gen_e_acsl_if,s,(void *)(& s));
    __gen_e_acsl_and_2 = __gen_e_acsl_valid;
    __gmpz_clear(__gen_e_acsl_n);
    __gmpz_clear(__gen_e_acsl_);
    __gmpz_clear(__gen_e_acsl_sub);
    __gmpz_clear(__gen_e_acsl__2);
    __gmpz_clear(__gen_e_acsl_sub_2);
    __gmpz_clear(__gen_e_acsl_add);
  }
  else __gen_e_acsl_and_2 = 0;
  return __gen_e_acsl_and_2;
}

int __gen_e_acsl_empty_block_here(void *s)
{
  unsigned long __gen_e_acsl_block_length;
  int __gen_e_acsl_and;
  __gen_e_acsl_block_length = __e_acsl_block_length(s);
  if (__gen_e_acsl_block_length == 0UL) {
    unsigned long __gen_e_acsl_offset;
    __gen_e_acsl_offset = __e_acsl_offset(s);
    __gen_e_acsl_and = __gen_e_acsl_offset == 0UL;
  }
  else __gen_e_acsl_and = 0;
  return __gen_e_acsl_and;
}

int __gen_e_acsl_valid_read_or_empty_here(void *s, unsigned long n)
{
  int __gen_e_acsl_empty_block_here_3;
  int __gen_e_acsl_or;
  int __gen_e_acsl_and;
  __gen_e_acsl_empty_block_here_3 = __gen_e_acsl_empty_block_here(s);
  if (__gen_e_acsl_empty_block_here_3) __gen_e_acsl_or = 1;
  else {
    int __gen_e_acsl_valid_read;
    __gen_e_acsl_valid_read = __e_acsl_valid_read(s,sizeof(char),s,
                                                  (void *)(& s));
    __gen_e_acsl_or = __gen_e_acsl_valid_read;
  }
  if (__gen_e_acsl_or) {
    __e_acsl_mpz_t __gen_e_acsl_size;
    __e_acsl_mpz_t __gen_e_acsl_sizeof;
    __e_acsl_mpz_t __gen_e_acsl_n;
    __e_acsl_mpz_t __gen_e_acsl_;
    __e_acsl_mpz_t __gen_e_acsl_sub;
    __e_acsl_mpz_t __gen_e_acsl_sub_2;
    __e_acsl_mpz_t __gen_e_acsl_add;
    __e_acsl_mpz_t __gen_e_acsl_mul;
    __e_acsl_mpz_t __gen_e_acsl__2;
    int __gen_e_acsl_le;
    __e_acsl_mpz_t __gen_e_acsl_if;
    __e_acsl_mpz_t __gen_e_acsl__4;
    int __gen_e_acsl_le_2;
    unsigned long __gen_e_acsl_size_2;
    int __gen_e_acsl_valid_read_2;
    __gmpz_init_set_si(__gen_e_acsl_sizeof,1L);
    __gmpz_init_set_ui(__gen_e_acsl_n,n);
    __gmpz_init_set_si(__gen_e_acsl_,1L);
    __gmpz_init(__gen_e_acsl_sub);
    __gmpz_sub(__gen_e_acsl_sub,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_));
    __gmpz_init(__gen_e_acsl_sub_2);
    __gmpz_sub(__gen_e_acsl_sub_2,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_sub),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_));
    __gmpz_init(__gen_e_acsl_add);
    __gmpz_add(__gen_e_acsl_add,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_sub_2),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_));
    __gmpz_init(__gen_e_acsl_mul);
    __gmpz_mul(__gen_e_acsl_mul,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_sizeof),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_add));
    __gmpz_init_set(__gen_e_acsl_size,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_mul));
    __gmpz_init_set_si(__gen_e_acsl__2,0L);
    __gen_e_acsl_le = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_size),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__2));
    if (__gen_e_acsl_le <= 0) {
      __e_acsl_mpz_t __gen_e_acsl__3;
      __gmpz_init_set_si(__gen_e_acsl__3,0L);
      __gmpz_init_set(__gen_e_acsl_if,
                      (__e_acsl_mpz_struct const *)(__gen_e_acsl__3));
      __gmpz_clear(__gen_e_acsl__3);
    }
    else __gmpz_init_set(__gen_e_acsl_if,
                         (__e_acsl_mpz_struct const *)(__gen_e_acsl_size));
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_3 =
      {.values = (void *)0};
    __gmpz_init_set_ui(__gen_e_acsl__4,18446744073709551615UL);
    __gen_e_acsl_le_2 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_if),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__4));
    __e_acsl_assert_register_mpz(& __gen_e_acsl_assert_data_3,
                                 "__gen_e_acsl_if",0,
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl_if));
    __gen_e_acsl_assert_data_3.blocking = 1;
    __gen_e_acsl_assert_data_3.kind = "RTE";
    __gen_e_acsl_assert_data_3.pred_txt = "(\\let size = sizeof(char) * (((n - 1) - 1) + 1); size <= 0? 0: size) <=\n18446744073709551615";
    __gen_e_acsl_assert_data_3.file = "FRAMAC_SHARE/libc/string.h";
    __gen_e_acsl_assert_data_3.fct = "valid_read_or_empty_here";
    __gen_e_acsl_assert_data_3.line = 52;
    __gen_e_acsl_assert_data_3.name = "offset_lesser_or_eq_than_SIZE_MAX";
    __e_acsl_assert(__gen_e_acsl_le_2 <= 0,& __gen_e_acsl_assert_data_3);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_3);
    __gen_e_acsl_size_2 = __gmpz_get_ui((__e_acsl_mpz_struct const *)(__gen_e_acsl_if));
    __gen_e_acsl_valid_read_2 = __e_acsl_valid_read((void *)((char *)s + 
                                                             1 * 1),
                                                    __gen_e_acsl_size_2,s,
                                                    (void *)(& s));
    __gen_e_acsl_and = __gen_e_acsl_valid_read_2;
    __gmpz_clear(__gen_e_acsl_size);
    __gmpz_clear(__gen_e_acsl_sizeof);
    __gmpz_clear(__gen_e_acsl_n);
    __gmpz_clear(__gen_e_acsl_);
    __gmpz_clear(__gen_e_acsl_sub);
    __gmpz_clear(__gen_e_acsl_sub_2);
    __gmpz_clear(__gen_e_acsl_add);
    __gmpz_clear(__gen_e_acsl_mul);
    __gmpz_clear(__gen_e_acsl__2);
    __gmpz_clear(__gen_e_acsl_if);
    __gmpz_clear(__gen_e_acsl__4);
  }
  else __gen_e_acsl_and = 0;
  return __gen_e_acsl_and;
}


