/* Generated by Frama-C */
/*@ \wp::strategy Prover: \prover("Alt-Ergo",0.1); */
/*@
\wp::strategy Lazy:
  Prover,
  \tactic("Wp.overflow",
    \pattern(\target:\any(P(_, (..)), Q((..)))),
    \select(\target)
    );
*/

